apiVersion: v1
kind: Service
metadata:  
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Kubefi
    release: nifi
  name: {{ name }}
spec:  
  ports:{{#if protocol.isSecure}}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{protocol.httpsPort}}{{else}}
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{protocol.httpPort}}{{/if}}
  selector:
    app: nifi
    release: nifi
  sessionAffinity: ClientIP
  type: ClusterIP