apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
    app.kubernetes.io/managed-by: Kubefi
    release: nifi
  name: {{ name }}-zookeeper-headless
spec:
  clusterIP: None
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
    - name: election
      port: 3888
      protocol: TCP
      targetPort: election
    - name: server
      port: 2888
      protocol: TCP
      targetPort: server
  selector:
    app: zookeeper
    release: nifi
  sessionAffinity: None
  type: ClusterIP