apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
    release: nifi
    app.kubernetes.io/managed-by: Kubefi
  name: {{ name }}-zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
  selector:
    app: zookeeper
    release: nifi
  sessionAffinity: None
  type: ClusterIP